### ISSUE TITLE
Not work in Neovim

### ISSUE THREAD

**Issue by anuvyklack** [bpstahlman/txtfmt#20]
I am using Neovim on Windows 10 1903, and when I am trying to execute command `:MakeTestPage` I get the error:
```
Level 1 map ambiguity:<lt> already mapped to <Plug>TxtfmtShiftLeft
Level 1 map ambiguity:> already mapped to <Plug>TxtfmtShiftRight
```
after that test page generated, but no highlighting enabled at all.

The same error occurs when I try `:set ft=txtfmt` in any file.

**Comment by bpstahlman** [comment]
Those warnings occur because the default map sequences for the left/right shift operators (`<` and `>`) and the normal mode shift commands (`<<` and `>>`) are ambiguous: i.e., when you type a single `>` or `<` in normal mode, neovim has to wait a bit to see whether you're going to type a second one or not. I will probably change the defaults to prevent this delay, though it's also possible to override the defaults and/or suppress the warning...

To suppress the warning and force the default map to be created in spite of the ambiguity...
```
let g:txtfmtMapwarn = 'c'
```
To avoid the warning by replacing `>` with `g>` and `<` with `g<`...
```
nmap g> <Plug>TxtfmtOperatorShiftRight
nmap g<lt> <Plug>TxtfmtOperatorShiftLeft

```

However, I don't think these warnings have anything to do with your highlighting issues. First of all, are you sure your vimrc enables syntax highlighting? It's not enabled automatically by Vim. Not sure about Neovim. Somewhere in your vimrc, you should have lines such as this:
```
filetype plugin indent on
syntax enable
```
Assuming you already have this... Are you using terminal or GUI neovim? If terminal, which one?
Also, what versions of Neovim and Txtfmt are you using?

**Comment by anuvyklack** [comment]
After I add  `let g:txtfmtMapwarn = 'c'` to my init.vim everything began work. I am using the  Neovim 4.0 nightly build (because only there is implemented pythonx provider) witn Neovim-Qt GUI. I installed the latest Txtfmt version with vim-plug.

**Comment by bpstahlman** [comment]
Glad to hear that fixed it. I'm surprised the warning was breaking highlighting. On my system, it doesn't... At any rate, I'll make sure the warning is suppressed in the next release. The ambiguity really isn't an issue: the same "ambiguity" exists with the native Vim versions of those commands. Typing either `>` / `<` or a motion specifier after the initial `>` / `<` resolves the ambiguity in favor of linewise and motion-based shift, respectively. Incidentally, I plan to make a release within the next couple weeks. It's a partial rewrite of the syntax engine, which makes highlighting _**much**_ faster in certain scenarios.
